import calendar

year = int(input("Enter year: "))
month = int(input("Enter month: "))
day = int(input("Enter day: "))

result = calendar.weekday(year, month, day)

print("Weekday Number (0=Mon to 6=Sun):", result)